# -*- coding: utf-8 -*-
"""Tarea03

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lTtQ1GU0O1i5itU0tvTBmfNzrcZmHE1K
"""

import matplotlib.pyplot as plt
import numpy as np
import cv2

img = cv2.imread('fallas.tif')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.figure(figsize=(20, 40))
plt.imshow(gray, cmap='gray')
plt.show()

img = cv2.imread('sun.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.imshow(gray, cmap='gray')
plt.show()

# ruido gaussiano

# ruido uniforme

# ruido impulsional-sal

# ruido impulsional-pimienta